### ISSUE TITLE
Questions about external objective evaluation

### ISSUE THREAD

**Issue by latmarat** [apaleyes/emukit#314]
Hello, I have a couple of questions about external objective evaluation. 

1. Can I control the number of next points I get in each iteration of manual loop? I can see there is [batch_size argument](https://github.com/amzn/emukit/blob/37473dd20b53f2f871bc82ff2358d483e4b43970/emukit/bayesian_optimization/loops/bayesian_optimization_loop.py#L34) in the GitHub code but it doesn't seem available in the version installed with pip. 

2. Is external objective evaluation mode [introduced for BO](https://nbviewer.jupyter.org/github/amzn/emukit/blob/master/notebooks/Emukit-tutorial-bayesian-optimization-external-objective-evaluation.ipynb) supported in Experimental Design as well? 

Thank you.

**Comment by apaleyes** [comment]
I think @latmarat means slightly different thing here, not initial designs

1. This depends on the method you are using. Most methods we implement right now aren't batch, so they will always give you 1 points. Local penalization is the example of a batch method, where setting batch_size indeed lets you control the number of points you get out at each iteration

2. Yes, get_next_points is supported by all methods in emukit, including exp design ones
